export const blogPosts = [
  { id: 26400, date: "2026-06-07", slug: "how-to-choose-an-ai-data-collection-partner-dserve-ai", title: "How to Choose an AI Data Collection Partner: A Complete Guide for Businesses", category: "Data Collection", readTime: "8 min" },
  { id: 26390, date: "2026-06-05", slug: "how-to-build-a-high-quality-ai-training-dataset", title: "How to Build a High-Quality AI Training Dataset: A Complete Guide", category: "Datasets", readTime: "10 min" },
  { id: 26383, date: "2026-06-02", slug: "best-data-annotation-services-for-ai-projects", title: "Best Data Annotation Services for AI Projects", category: "Annotation", readTime: "7 min" },
  { id: 26370, date: "2026-05-28", slug: "best-practices-for-creating-accurate-ai-training-datasets", title: "Best Practices for Creating Accurate AI Training Datasets", category: "Datasets", readTime: "9 min" },
  { id: 26361, date: "2026-05-27", slug: "why-businesses-need-custom-ai-datasets", title: "Why Businesses Need Custom AI Datasets", category: "Custom Data", readTime: "6 min" },
  { id: 26349, date: "2026-05-23", slug: "building-hipaa-compliant-ai-datasets-for-healthcare-innovation", title: "Building HIPAA-Compliant AI Datasets for Healthcare Innovation", category: "Healthcare AI", readTime: "11 min" },
  { id: 26343, date: "2026-05-23", slug: "why-generative-ai-needs-high-quality-training-data", title: "Why Generative AI Needs High-Quality Training Data", category: "Gen AI", readTime: "8 min" },
  { id: 26318, date: "2026-05-05", slug: "best-data-annotation-company-for-scalable-ai-solutions-in-2026", title: "Data Annotation Company: How to Choose the Right Partner for AI Success in 2026", category: "Annotation", readTime: "9 min" },
  { id: 26312, date: "2026-05-04", slug: "data-annotation-services-the-foundation-of-high-performance-ai-in-2026", title: "Data Annotation Services: The Foundation of High-Performance AI in 2026", category: "Annotation", readTime: "10 min" },
  { id: 26287, date: "2026-04-29", slug: "ai-gold-rush-2026-why-data-companies-are-the-real-winners", title: "AI Gold Rush 2026: Why Data Companies Are the Real Winners", category: "Industry", readTime: "7 min" },
  { id: 26267, date: "2026-04-25", slug: "speech-dataset-collection-for-conversational-ai-in-2026", title: "Speech Dataset Collection for Conversational AI in 2026", category: "Audio Data", readTime: "8 min" },
  { id: 26261, date: "2026-04-24", slug: "ai-in-2026-why-data-quality-matters-more-than-model-size", title: "AI in 2026: Why Data Quality Matters More Than Model Size", category: "Quality", readTime: "6 min" },
  { id: 26229, date: "2026-04-16", slug: "build-vs-buy-dataset-should-you-create-or-outsource-your-ai-data", title: "Build vs Buy Dataset: Should You Create or Outsource Your AI Data?", category: "Strategy", readTime: "9 min" },
  { id: 26220, date: "2026-04-16", slug: "how-ai-startups-can-scale-faster-with-quality-data", title: "How AI Startups Can Scale Faster with Quality Data", category: "Startups", readTime: "7 min" },
  { id: 26213, date: "2026-04-08", slug: "how-to-ensure-data-diversity-in-ai-training-complete-guide-2026", title: "How to Ensure Data Diversity in AI Training (Complete Guide 2026)", category: "Datasets", readTime: "11 min" },
  { id: 26195, date: "2026-04-06", slug: "manual-vs-automated-data-annotation-which-is-better-in-2026", title: "Manual vs Automated Data Annotation: Which is Better for AI in 2026?", category: "Annotation", readTime: "8 min" },
  { id: 26190, date: "2026-04-05", slug: "semantic-segmentation-vs-instance-segmentation-explained", title: "Semantic Segmentation vs Instance Segmentation Explained", category: "Computer Vision", readTime: "9 min" },
  { id: 26165, date: "2026-03-30", slug: "where-to-get-high-quality-training-data-for-ai-models", title: "Where to Get High-Quality Training Data for AI Models", category: "Datasets", readTime: "7 min" },
  { id: 26136, date: "2026-03-27", slug: "best-data-annotation-services-for-ai-companies", title: "Best Data Annotation Services for AI Companies: Why Dserve AI Stands Out", category: "Annotation", readTime: "8 min" },
  { id: 26098, date: "2026-03-24", slug: "how-companies-like-tesla-and-google-rely-on-data-annotation", title: "How Companies Like Tesla and Google Rely on Data Annotation", category: "Industry", readTime: "10 min" },
  { id: 26041, date: "2026-03-20", slug: "data-annotation-services-complete-guide-for-ai-businesses-2026", title: "Data Annotation Services: Complete Guide for AI Businesses (2026)", category: "Annotation", readTime: "12 min" },
  { id: 26009, date: "2026-03-18", slug: "top-challenges-in-data-annotation-and-how-to-solve-them-in-2026", title: "Top Challenges in Data Annotation and How to Solve Them in 2026", category: "Annotation", readTime: "9 min" },
  { id: 25989, date: "2026-03-16", slug: "how-businesses-use-custom-ai-datasets-to-build-smarter-models", title: "How Businesses Use Custom AI Datasets to Build Smarter Models", category: "Custom Data", readTime: "8 min" },
  { id: 25958, date: "2026-03-14", slug: "how-startups-can-train-ai-models-without-huge-datasets-dserve-ai", title: "How Startups Can Train AI Models Without Huge Datasets", category: "Startups", readTime: "7 min" },
];

export const caseStudies = [
  {
    id: 1,
    slug: "healthcare-diagnostics-ai",
    title: "Healthcare Diagnostics AI",
    description: "Delivered 500K+ annotated medical images for a leading diagnostic AI startup, achieving 98.7% annotation accuracy.",
    fullDescription: "A leading healthcare AI startup needed a massive, high-quality dataset of annotated medical images to train their diagnostic model. Dserve AI collected and annotated over 500,000 X-ray, CT, and MRI images with precise bounding boxes and segmentation masks. Our expert medical annotators worked under strict HIPAA compliance protocols, ensuring every image was labeled with clinical accuracy. The resulting dataset helped the client's model achieve a 98.7% accuracy rate in early disease detection trials — outperforming the industry benchmark by 12%.",
    industry: "Healthcare",
    result: "98.7% accuracy",
    tags: ["Medical Imaging", "Annotation", "HIPAA"],
    color: "#3b82f6",
    stats: [{ v: "500K+", l: "Images Annotated" }, { v: "98.7%", l: "Accuracy Rate" }, { v: "3 Weeks", l: "Delivery Time" }],
  },
  {
    id: 2,
    slug: "autonomous-vehicle-perception",
    title: "Autonomous Vehicle Perception",
    description: "Built comprehensive multi-modal datasets (LiDAR, camera, radar) for an AV company's perception stack.",
    fullDescription: "A top-tier autonomous vehicle company needed diverse, multi-modal perception data to train their self-driving stack. Dserve AI built a comprehensive dataset combining synchronized LiDAR point clouds, front and surround-view camera footage, and radar readings across 50+ driving environments — including adverse weather, night-time, and construction zones. Each scene was annotated with 3D bounding boxes, lane markings, and drivable area segmentation, resulting in over 2 million individually labeled data points delivered in KITTI and nuScenes formats.",
    industry: "Automotive",
    result: "2M+ data points",
    tags: ["Computer Vision", "LiDAR", "Object Detection"],
    color: "#8b5cf6",
    stats: [{ v: "2M+", l: "Data Points" }, { v: "50+", l: "Environments" }, { v: "3 Formats", l: "Delivered In" }],
  },
  {
    id: 3,
    slug: "conversational-ai-training",
    title: "Conversational AI Training",
    description: "Collected and annotated 1M+ diverse voice samples across 50+ languages for a global NLP model.",
    fullDescription: "A global technology company building a multilingual conversational AI needed authentic, diverse voice and text data across 50+ languages and dialects. Dserve AI orchestrated a worldwide data collection effort, recruiting native speakers across all target languages and recording naturalistic conversations, commands, and queries in varied acoustic environments. All audio was transcribed, speaker-diarized, and tagged with emotion and intent labels. The dataset enabled the client's model to achieve state-of-the-art word error rates across 12 of the 50 tested languages.",
    industry: "Conversational AI",
    result: "50+ languages",
    tags: ["Speech Data", "NLP", "Multilingual"],
    color: "#06b6d4",
    stats: [{ v: "1M+", l: "Voice Samples" }, { v: "50+", l: "Languages" }, { v: "95%+", l: "IAA Score" }],
  },
  {
    id: 4,
    slug: "e-commerce-visual-search",
    title: "E-Commerce Visual Search",
    description: "Created 300K product images with precise attribute labels enabling 95% accurate visual search.",
    fullDescription: "A major e-commerce platform wanted to launch a visual search feature that could identify products from user-uploaded photos. Dserve AI created a dataset of 300,000 product images spanning 80+ categories, each annotated with fine-grained attributes including color, texture, material, shape, and style tags. We also collected lifestyle images showing products in natural context to improve real-world retrieval accuracy. The platform launched their visual search feature with a 95% retrieval accuracy — increasing product discovery by 34% in the first quarter.",
    industry: "E-Commerce",
    result: "95% search accuracy",
    tags: ["Image Classification", "Retail", "Custom Data"],
    color: "#ec4899",
    stats: [{ v: "300K", l: "Product Images" }, { v: "80+", l: "Categories" }, { v: "95%", l: "Retrieval Accuracy" }],
  },
  {
    id: 5,
    slug: "marine-safety-ai",
    title: "Marine Safety AI",
    description: "Custom maritime datasets covering vessel detection, ocean weather patterns, and collision avoidance.",
    fullDescription: "A maritime technology firm developing an AI-powered collision avoidance system needed highly specialized data from ocean environments. Dserve AI collected multi-spectral and thermal imagery of open-sea scenarios, port operations, and coastal navigation, annotating vessels by class, heading, and AIS compliance status. Weather metadata and wave-condition tags were layered in to help the model understand environmental risk factors. The resulting system was certified to improve route safety by 40% in independent maritime authority trials.",
    industry: "Maritime",
    result: "40% safer routes",
    tags: ["Object Detection", "Maritime", "Safety AI"],
    color: "#f59e0b",
    stats: [{ v: "40%", l: "Safety Improvement" }, { v: "12", l: "Vessel Classes" }, { v: "5 Seas", l: "Data Collected" }],
  },
  {
    id: 6,
    slug: "biometric-verification-system",
    title: "Biometric Verification System",
    description: "Diverse face and fingerprint datasets spanning 80+ ethnicities for a global identity verification platform.",
    fullDescription: "A global identity verification platform needed an ethically sourced, highly diverse biometric dataset to power a fair and accurate AI verification system. Dserve AI collected face images, fingerprint scans, and iris photos from consenting participants across 80+ ethnicities and age groups in 30+ countries. Anti-spoofing samples (printed photos, masks, screen replays) were also included to harden liveness detection. The resulting system achieved sub-0.1% false-accept rates while reducing demographic bias gaps by 60% compared to the client's previous model.",
    industry: "Security",
    result: "80+ demographics",
    tags: ["Biometric", "Face Recognition", "Privacy"],
    color: "#10b981",
    stats: [{ v: "80+", l: "Ethnicities" }, { v: "30+", l: "Countries" }, { v: "<0.1%", l: "False Accept Rate" }],
  },
];

export const services = [
  {
    slug: "custom-dataset-collection",
    iconName: "database",
    title: "Custom Dataset Collection",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2000",
    description: "We capture and source the exact data you need. From audio to video, we deliver diverse, ethically gathered datasets ready for engineering teams.",
    features: ["On-demand collection worldwide", "Any modality supported", "Ethical sourcing with consent", "Rich metadata included"],
    color: "#3b82f6",
    details: {
      overview: "Our custom dataset collection service gives you complete control over what data you need. We source from real-world environments across the globe, ensuring your training data reflects the diversity your model needs to perform at production scale.",
      what: ["Image & Video Collection", "Audio & Speech Recording", "Text Corpus Curation", "LiDAR & Sensor Data", "Multi-modal Dataset Builds"],
      how: "Our global network of data collectors follows your exact specification brief — capturing the right demographics, environments, lighting conditions, and languages. Every collection campaign is managed end-to-end with real-time progress dashboards.",
      formats: ["COCO JSON", "Pascal VOC", "YOLO", "Custom formats on request"],
    },
  },
  {
    slug: "data-annotation-labeling",
    iconName: "tag",
    title: "Data Annotation & Labeling",
    imageUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=2000",
    description: "Pixel-perfect bounding boxes, segmentation masks, and NLP labeling. Our expert teams deliver the highly accurate annotations required for production models.",
    features: ["Bounding boxes & polygons", "Semantic segmentation", "Keypoints & landmarks", "Text transcription & NER"],
    color: "#8b5cf6",
    details: {
      overview: "Our annotation teams combine domain expertise with rigorous quality protocols. Whether you need pixel-level segmentation or complex NLP labeling, we deliver production-ready annotations at scale.",
      what: ["Bounding Box Annotation", "Semantic & Instance Segmentation", "Keypoint & Pose Estimation", "Text & NER Labeling", "Audio Transcription & Diarization"],
      how: "Annotations go through a 3-stage review: primary annotator, QA specialist review, and automated consistency checks. We maintain Inter-Annotator Agreement (IAA) scores above 95% on all projects.",
      formats: ["COCO JSON", "Pascal VOC XML", "YOLO TXT", "CONLL", "CSV/JSON-L"],
    },
  },
  {
    slug: "quality-assurance",
    iconName: "shieldCheck",
    title: "Quality Assurance",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=2000",
    description: "We don't ship data without rigorous testing. Our QA teams verify accuracy and consistency to ensure your training sets are flawless.",
    features: ["Multi-stage QA pipeline", "Inter-annotator agreement", "Automated consistency checks", "Metadata enrichment"],
    color: "#06b6d4",
    details: {
      overview: "Quality is not a feature — it is the foundation of everything we deliver. Our dedicated QA infrastructure ensures every data point meets the exacting standards required to train production-grade AI models.",
      what: ["Annotation Accuracy Audits", "Consistency & Bias Checks", "Data Distribution Analysis", "Metadata Validation", "Sample-level Review Reports"],
      how: "Each dataset undergoes automated statistical checks followed by human expert review. We provide full QA reports with confidence scores and flag edge cases for your team's review before final delivery.",
      formats: ["Full QA Report (PDF)", "Per-sample confidence scores", "Bias & distribution dashboards"],
    },
  },
  {
    slug: "rapid-dataset-delivery",
    iconName: "zap",
    title: "Rapid Dataset Delivery",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=2000",
    description: "We know speed is critical. We deliver clean, structured data in your preferred formats exactly when you need it, without sacrificing quality.",
    features: ["Fast turnaround guaranteed", "Custom output formats", "Secure cloud delivery", "Revision cycles included"],
    color: "#ec4899",
    details: {
      overview: "Time-to-data is a competitive advantage. Our streamlined delivery pipeline ensures you never wait longer than necessary — with milestone-based progress updates and secure delivery directly to your cloud storage.",
      what: ["Priority Delivery Lanes", "Cloud-to-Cloud Transfer", "Incremental Batch Delivery", "Format Conversion", "Post-delivery Revision Support"],
      how: "We assign dedicated project managers to every engagement who track progress in real time, proactively flagging risks and adjusting capacity to meet your deadline — guaranteed.",
      formats: ["AWS S3", "Google Cloud Storage", "Azure Blob", "SFTP", "Direct Download"],
    },
  },
  {
    slug: "healthcare-ai-datasets",
    iconName: "heartPulse",
    title: "Healthcare AI Datasets",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=2000",
    description: "Strictly compliant, high-quality medical data. We support healthcare teams with imaging, clinical text, and diagnostics data built under secure protocols.",
    features: ["HIPAA & GDPR compliant", "Medical imaging data", "Clinical text & EHR", "Genomics & bioinformatics"],
    color: "#10b981",
    details: {
      overview: "Healthcare AI demands the highest data quality and strictest compliance standards. Our dedicated healthcare data division has delivered millions of medical data points to diagnostic AI companies, research institutions, and pharmaceutical firms worldwide.",
      what: ["X-Ray, CT & MRI Annotation", "Pathology Slide Analysis", "Clinical Text & EHR Datasets", "Genomics Research Data", "Doctor-Patient Conversation Data"],
      how: "All healthcare projects are handled by annotators with medical domain training, operating under BAA agreements and HIPAA-compliant workflows. Data is de-identified and stored in encrypted, access-controlled environments.",
      formats: ["DICOM", "HL7 FHIR", "CSV/JSON", "CONLL (for NLP)", "Custom clinical formats"],
    },
  },
  {
    slug: "computer-vision-data",
    iconName: "eye",
    title: "Computer Vision Data",
    imageUrl: "https://images.unsplash.com/photo-1527430253228-e93688616381?auto=format&fit=crop&q=80&w=2000",
    description: "High-quality visual data for complex models. We handle object detection, classification, and segmentation tasks for specialized computer vision applications.",
    features: ["Object detection datasets", "Semantic segmentation", "Video tracking data", "OCR & document AI"],
    color: "#f59e0b",
    details: {
      overview: "Computer vision models are only as good as the visual data they learn from. We specialize in building visually rich, precisely annotated datasets that cover the full spectrum of CV tasks — from basic classification to complex multi-object 3D scene understanding.",
      what: ["Object Detection & Localization", "Semantic & Instance Segmentation", "Image Classification", "Action & Activity Recognition", "OCR & Document Understanding", "3D Point Cloud Annotation"],
      how: "Our CV-specialized annotators use professional tools (CVAT, Scale AI-compatible exports, Roboflow-ready formats) to deliver pixel-perfect results. We can match any existing annotation schema for seamless integration.",
      formats: ["COCO JSON", "Pascal VOC", "YOLO", "TFRecord", "Open Images format"],
    },
  },
];

export const industries = [
  {
    slug: "healthcare-ai",
    iconName: "heartPulse",
    name: "Healthcare AI",
    desc: "Medical imaging, diagnostics, clinical text & genomics",
    color: "#10b981",
    details: {
      overview: "We power AI systems that are changing medicine — from early disease detection to drug discovery. Our HIPAA-compliant medical datasets span imaging, clinical text, genomics, and patient interaction data.",
      capabilities: ["X-Ray & CT Annotation", "Pathology Image Datasets", "EHR & Clinical NLP", "Drug Discovery Data", "Patient Conversation Corpora"],
      stat: "500K+ medical images delivered",
    },
  },
  {
    slug: "computer-vision",
    iconName: "eye",
    name: "Computer Vision",
    desc: "Object detection, classification & segmentation",
    color: "#f59e0b",
    details: {
      overview: "From autonomous drones to retail shelf analysis, our computer vision datasets are built for real-world complexity. We cover the full range of CV tasks with industry-leading annotation precision.",
      capabilities: ["Object Detection", "Semantic Segmentation", "Action Recognition", "3D Point Clouds", "OCR & Document AI"],
      stat: "2M+ images annotated for CV projects",
    },
  },
  {
    slug: "agentic-ai",
    iconName: "bot",
    name: "Agentic AI",
    desc: "Autonomous agents, decision loops & tool-use training data",
    color: "#3b82f6",
    details: {
      overview: "Agentic AI systems need training data that captures real-world decision chains, tool-use trajectories, and multi-step reasoning. We build the specialized datasets that teach agents to plan, act, and self-correct across complex workflows.",
      capabilities: ["Agent Trajectory Datasets", "Tool-Use Annotation", "Reasoning Chain Labeling", "RLHF Preference Data", "Multi-Step Task Demonstrations"],
      stat: "Used by agentic AI teams at 20+ organizations",
    },
  },
  {
    slug: "generative-ai",
    iconName: "sparkles",
    name: "Generative AI",
    desc: "Prompt datasets, RLHF & synthetic data pipelines",
    color: "#a855f7",
    details: {
      overview: "Generative AI quality starts with training data quality. We specialize in instruction tuning datasets, RLHF preference pairs, prompt-response corpora, and safety alignment data that makes generative models both capable and responsible.",
      capabilities: ["Instruction Tuning Data", "RLHF Preference Pairs", "Prompt Diversity Curation", "Safety & Alignment Data", "Synthetic Data Augmentation"],
      stat: "100K+ RLHF preference pairs delivered",
    },
  },
  {
    slug: "multimodal-ai",
    iconName: "layers",
    name: "Multimodal AI",
    desc: "Image-text, audio-visual & cross-modal training datasets",
    color: "#ec4899",
    details: {
      overview: "Multimodal AI requires data that spans multiple modalities simultaneously — and alignment between them. We build image-text pairs, audio-visual corpora, and cross-modal annotation pipelines that enable models to understand the world in context.",
      capabilities: ["Image-Text Pair Datasets", "Audio-Visual Alignment Data", "Video-Caption Corpora", "Cross-Modal Retrieval Data", "Visual Question Answering Sets"],
      stat: "Multi-modal datasets delivered for 15+ foundation model teams",
    },
  },
  {
    slug: "biometric-ai",
    iconName: "fingerprint",
    name: "Biometric AI",
    desc: "Diverse face, fingerprint & iris recognition datasets",
    color: "#06b6d4",
    details: {
      overview: "Biometric AI requires ethical, diverse, and rigorously collected datasets. We source biometric data from consenting participants across 80+ demographics, with anti-spoofing samples built in.",
      capabilities: ["Face Recognition Datasets", "Fingerprint Collection", "Iris Recognition Data", "Liveness Detection Samples", "Anti-Spoofing Datasets"],
      stat: "80+ ethnicities represented in biometric collections",
    },
  },
  {
    slug: "geospatial-ai",
    iconName: "globe",
    name: "Geospatial AI",
    desc: "Satellite imagery, mapping & terrain analysis datasets",
    color: "#0ea5e9",
    details: {
      overview: "Geospatial AI depends on high-resolution, precisely annotated earth observation data. We build satellite and aerial imagery datasets for land use classification, change detection, disaster response, and infrastructure monitoring — at planetary scale.",
      capabilities: ["Satellite Imagery Annotation", "Land Use Classification", "Change Detection Datasets", "Terrain & Elevation Data", "Infrastructure Mapping"],
      stat: "Geospatial datasets covering 40+ countries delivered",
    },
  },
  {
    slug: "conversational-ai",
    iconName: "messageSquare",
    name: "Conversational AI",
    desc: "Speech datasets & NLP across 50+ languages",
    color: "#8b5cf6",
    details: {
      overview: "Natural conversation is hard to simulate — we collect it authentically. Our conversational AI datasets span 50+ languages and include ASR, NLU, sentiment, emotion, and dialogue datasets for chatbots and voice assistants.",
      capabilities: ["Multilingual Speech Collection", "Dialogue Act Annotation", "Sentiment & Emotion Tagging", "Intent Classification Data", "TTS & ASR Datasets"],
      stat: "1M+ voice samples across 50+ languages",
    },
  },
];

export const stats = [
  { value: "1M+", label: "AI Data Units Generated", desc: "Powering innovations across industries" },
  { value: "50+", label: "Dataset Categories", desc: "Supported across all domains" },
  { value: "100%", label: "Quality Guarantee", desc: "Unmatched data accuracy" },
  { value: "15+", label: "Years Experience", desc: "In AI data services" },
];

export const partners = [
  { name: "AWS", abbr: "AWS" },
  { name: "Google", abbr: "Google" },
  { name: "Microsoft", abbr: "MSFT" },
  { name: "NVIDIA", abbr: "NVDA" },
  { name: "Scale AI", abbr: "Scale" },
  { name: "OpenAI", abbr: "OAI" },
  { name: "Meta", abbr: "META" },
  { name: "Philips", abbr: "PHG" },
  { name: "Polytope", abbr: "POLY" },
];

export const faqs = [
  { q: "What types of datasets does Dserve AI provide?", a: "We provide custom datasets across all modalities: images, video, audio, text, LiDAR, and multi-modal data. We cover 50+ categories spanning healthcare, computer vision, NLP, autonomous vehicles, biometrics, and more." },
  { q: "How long does it take to receive my dataset?", a: "Turnaround depends on dataset size and complexity. Small datasets (10K-50K units) typically complete in 5-10 business days. Large datasets (1M+ units) are delivered on custom timelines agreed upfront. We always prioritize speed without compromising quality." },
  { q: "Is the data ethically sourced and compliant?", a: "Absolutely. All our data is sourced with explicit consent, adhering to GDPR, HIPAA, and CCPA regulations where applicable. We maintain full audit trails and data provenance documentation." },
  { q: "Can we request a pilot project before a full commitment?", a: "Yes! We encourage clients to request a pilot project to evaluate our engineering capabilities, data quality, and custom pipeline integration before executing a full enterprise agreement." },
  { q: "What annotation formats do you support?", a: "We support all industry-standard formats: COCO JSON, Pascal VOC XML, YOLO TXT, CSV, JSON-L, CONLL, and custom formats upon request. We can adapt to your ML pipeline's requirements." },
  { q: "Do you work with healthcare AI and HIPAA-regulated data?", a: "Yes. We have extensive experience delivering HIPAA-compliant medical datasets including X-ray, CT, MRI, pathology images, clinical notes, and genomic data. All healthcare projects include BAA agreements." },
  { q: "How is annotation quality ensured?", a: "Every annotation goes through 3-stage quality control: annotator review, QA specialist review, and automated consistency checks. We maintain IAA (Inter-Annotator Agreement) scores above 95% for all projects." },
  { q: "Can Dserve AI handle large-scale projects (millions of data points)?", a: "Yes. We have the infrastructure and workforce to scale to millions of data points. We've successfully delivered 1M+ unit projects for enterprise clients with strict deadlines and quality standards." },
];

export const process = [
  { step: "01", title: "Project Scoping & Taxonomy", desc: "Define your exact data parameters, labeling taxonomies, and compliance requirements. We map out edge cases and establish a custom tooling pipeline tailored to your model's architecture." },
  { step: "02", title: "Sourcing & Precision Labeling", desc: "We deploy specialized workforces to capture or generate raw data, followed by high-precision annotation. Every bounding box, polygon, and transcription is executed strictly to your rubric." },
  { step: "03", title: "Multi-Stage QA Auditing", desc: "A combination of automated statistical scripts and senior human reviewers audit the data. We enforce strict consensus thresholds to guarantee >99% accuracy before delivery." },
  { step: "04", title: "Delivery & Iteration", desc: "Receive fully structured, model-ready datasets via API or secure bucket transfer. We remain engaged for continuous feedback loops, active learning, and edge-case refinement." },
];

export const testimonials = [
  { name: "Dr. Sarah Chen", role: "Head of AI Research, MedVision Labs", text: "Dserve AI delivered 500,000 annotated radiology images with 99% accuracy in just 3 weeks. Our diagnostic model's performance improved dramatically. Truly world-class.", rating: 5 },
  { name: "Marcus Williams", role: "CTO, AutoDrive Systems", text: "The diversity and richness of Dserve's LiDAR and camera datasets was unlike anything we'd seen. Their team understood our perception requirements perfectly.", rating: 5 },
  { name: "Priya Krishnamurthy", role: "VP Engineering, Lingual AI", text: "We needed speech data across 40 languages with natural variation. Dserve collected and annotated it in record time. The quality was exceptional.", rating: 5 },
];
